[package]
name = "minidb-bench"
version = "0.1.0"
authors = ["Julian Tescher <jatescher@gmail.com>"]

[dependencies]
histogram = "0.6.7"
futures = "0.1"
tokio-core = "0.1"
tokio-io = "0.1"
rand = "0.3"
